[gh-174] Add C++ support
hpyproject/hpy pull request #283
Opened 2022-01-31 02:45 UTC by qunaibit

In the effort of porting `matplotlib` library, which is heavily implemented in C++, `void *` pointers need to be replaced with function pointers in addition to other adjustments.

I'v add C++ proof-of-concept to the current `./proof-of-concept` as a test case for the C++ support.

2022-02-01 09:21 UTC, thedrow requested changes
We need infer to verify the code when compiling using C++ as well.

2022-02-01 09:34 UTC, qunaibit commented
The verification is in the `C++ proof-of-concept` and it's checked as part of the `
tests / Proof of concept tests`

2022-02-09 08:59 UTC, fangerer commented
@thedrow I'm not sure if I understand. Do you mean we should run `infer` on the C++ proof-of-concept?

2022-02-09 10:50 UTC, thedrow commented
> @thedrow I'm not sure if I understand. Do you mean we should run `infer` on the C++ proof-of-concept?

No. What you need to do is build the code using a C++ compiler and let infer inspect that.
[Here](https://github.com/hpyproject/hpy/blob/master/Makefile#L48) we build the extension using a C compiler.
We should verify that there's no difference at the very least because C++ has different rules than C.

2022-02-15 00:28 UTC, qunaibit commented
> What you need to do is build the code using a C++ compiler

Unfortunately, doing so raise couple of errors for `hpy/debug/src/_debugmod.c`:
```
error: taking address of temporary array
error: jump to label ‘error’
```

> verify that there's no difference at the very least

HPy itself will always be compiled using `C` compiler. The modifications are mainly for header files that will be included in users' C++ extensions.

2022-02-15 21:28 UTC, qunaibit commented
> we need to somehow verify that they export all the symbols correctly

HPy's symbols won't be affect by the target as it is self contained and compiled without mangling.

> we're not breaking any linter rules on that target.

linter rules for HPy can be a great addition, but out-of-scope of this PR as linter can also be applied to `C`-based extensions.

> If you're satisfied with the way things currently are

I believe so.

Thanks for the comments and suggestions

2022-02-17 13:51 UTC, rlamy commented
LGTM. Having to explicitly cast all the `void*` is a bit annoying though. Is there any way to avoid it?

2022-02-17 17:35 UTC, qunaibit commented
> Having to explicitly cast all the void* is a bit annoying though. Is there any way to avoid it?

Unfortunately, no. C++ preprocessor is very strict with function pointers.
I've tried to hide those changes from user's extension, so this should not affect any prior c ext implementations.

2022-02-17 18:36 UTC, rlamy commented
OK, we'll have to live with it, then. I'll merge.

2022-02-17 18:37 UTC, merged