Support parsing nested tuples in HPyArg_Parse
hpyproject/hpy pull request #284
Opened 2022-01-31 03:02 UTC by qunaibit

In the effort of porting `matplotlib` library, there are multiple places where `()` are being used in argparse formats.

2022-02-15 10:44 UTC, steve-s commented
The 'O' formats in tuples/lists should have tests otherwise lgtm

2022-02-17 19:09 UTC, rlamy requested changes
Looks good overall. I'm a bit unsure about the fatal errors actually. I know CPython does it that way, but wouldn't it be better to raise SystemError instead?

2022-02-17 22:00 UTC, hodgestar commented
I would like to put in a vote for *not* parsing nest tuples, for the following reasons:

1. I think this exists in Python to provide a C alternative to tuple unpacking in Python function signatures. That feature caused all sorts of issues and no longer exists.
2. The nested bracketing makes the parsing a lot more complicated to reason about.
3. I'm not really sure what the advantage of it is over just unpacking the tuple into a handle and then calling the necessary functions to extract the tuple elements individually (e.g. `HPy_GetItem_i` or `HPy_GetItem_s`).

Perhaps there really are lots of uses out there that are hard to port though?

2022-02-19 02:00 UTC, qunaibit commented
> That feature caused all sorts of issues and no longer exists.

It still exist and very much in use as per CPython doc: "[Format units for sequences may be nested.](https://docs.python.org/3/c-api/arg.html#c.PyArg_ParseTuple)"

The other two reasons have a point. As you said this can be replace with exiting APIs.

This PR is just to ease the porting effort, and it is not essential.

2022-02-20 21:06 UTC, hodgestar commented
> > That feature caused all sorts of issues and no longer exists.
> 
> It still exist and very much in use as per CPython doc: "[Format units for sequences may be nested.](https://docs.python.org/3/c-api/arg.html#c.PyArg_ParseTuple)"

I didn't mean `PyArg_Parse`, I meant `def f((x, y)): ...` which existed in Python 2.

2022-02-20 22:37 UTC, qunaibit commented
That's not part of this PR. This PR just reuse existing mechanics of HPy's 'argparse'

2022-02-21 06:09 UTC, hodgestar commented
@qunaibit Would you mind trying to understand my point? Perhaps I am not explaining it well, but you are replying with unrelated rebuttals instead of asking for clarification. The point I am trying to make is that `def f((x, y)):` is no longer valid Python syntax and parsing nested tuples in `PyArg_ParseTuple` is the equivalent C functionality, so although the C functionality still exists, it is less useful than it was.

2022-02-21 07:21 UTC, closed without merging

2022-02-21 07:26 UTC, hodgestar commented
I didn't intend to end the conversation. If there are a lot of use cases or porting without it is hard or performance is bad, we could definitely add it. I am just pushing back a little on adding all the features of the existing C API.

2022-02-21 09:00 UTC, qunaibit commented
In top 4000: there are 35 usage of this pattern within 19 files. It's not a lot.

2022-02-21 10:00 UTC, hodgestar commented
Thank you for checking!